my_blog/urls.py
# -*- coding: utf-8 -*-
# @ProjectName  : myblog
# @Time    : 2018/7/2 15:18
# @Author  : CHEN HUI   @iuntouch
# @Email   : huch7280@tju.edu.cn
# @File    : urls.py
# @Software: PyCharm


from django.urls import re_path, include
from . import views


urlpatterns = [
    re_path(r'^$', views.login),
    re_path(r'^index/$', views.index),
    re_path(r'^register/$', views.register),
    re_path(r'^(.*?)/newblog/$', views.newBlog),
    re_path(r'^(.*?)/$', views.blog),

]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('my_blog.urls')),
]

my_blog/models.py
from django.db import models
from tinymce.models import HTMLField


# Create your models here.
# 创建用户管理器
class UserManager(models.Manager):
    def createUser(self, username, gender, email, password, birthday, contend, isDelete=False):
        user = self.model()
        user.username = username
        user.gender = gender
        user.email = email
        user.password = password
        user.birthday  = birthday
        user.contend = contend
        return user


class User(models.Model):
    userobj = UserManager()
    username = models.CharField(max_length=20, unique=True)
    gender = models.BooleanField(default=True)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=20)
    birthday = models.DateField()
    contend = models.CharField(max_length=40)
    isDelete = models.BooleanField(default=False)

    class Meta:
        db_table = "users"
        ordering = ["id"]

    def __str__(self):
        return self.username


# 创建博客管理器
class BlogManager(models.Manager):
    def get_queryset(self):
        return super(BlogManager, self).get_queryset().filter(isDelete=False)

    def createBlog(self, title, summary, body, author, isDelete=False):
        blog = self.model()
        blog.title = title
        blog.summary = summary
        blog.body = body
        blog.author = author
        return blog


class Blog(models.Model):
    blogobj = BlogManager()
    title = models.CharField(max_length=100)
    postDate = models.DateTimeField(auto_now_add=True)
    summary = models.CharField(max_length=150)
    body = HTMLField()
    isDelete = models.BooleanField(default=False)
    author = models.ForeignKey("User", on_delete=models.CASCADE)

    class Meta:
        db_table = "blogs"
        ordering = ["id"]

    def __str__(self):
        return self.title

my_blog/forms/forms.py
# -*- coding: utf-8 -*-
# @ProjectName  : myblog
# @Time    : 2018/7/5 11:19
# @Author  : CHEN HUI   @iuntouch
# @Email   : huch7280@tju.edu.cn
# @File    : forms.py
# @Software: PyCharm


from django import forms
from ..models import User
from tinymce.models import HTMLField


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, required=True, error_messages={"0": "用户名已注册"})
    gender = forms.ChoiceField(required=True, choices=((1, "男"), (0, "女")), initial=1, widget=forms.RadioSelect)
    email = forms.EmailField(max_length=30, required=True)
    password = forms.CharField(max_length=20, required=True, widget=forms.PasswordInput)
    reptpassword = forms.CharField(max_length=20, required=True, widget=forms.PasswordInput)
    birthday = forms.DateField(required=True)
    contend = forms.CharField(max_length=40)

    def checkpassword(self):
        password = self.cleaned_data["password"]
        reptpassword = self.cleaned_data["reptpassword"]
        if password != reptpassword:
            return False
        return True

    def checkusername(self):
        try:
            username = self.cleaned_data["username"]
        finally:
            usernames = list(User.userobj.get_queryset().values_list("username"))
            for user in usernames:
                if username in user:
                    return False
            return True


class BlogForm(forms.Form):
    title = forms.CharField(max_length=100)
    summary = forms.CharField(max_length=150)
    body = HTMLField()
    author = forms.CharField(max_length=20)

my_blog/views.py
from django.shortcuts import render, redirect
from .models import User, Blog
from .forms.forms import RegisterForm, BlogForm


# Create your views here.
def login(request):
    return render(request, "my_blog/login.html")


def index(request):
    if request.method == "POST":
        username = request.POST.get("username")
        if not username:
            return render(request, "my_blog/login.html")
        if not User.userobj.get_queryset().filter(username=username):
            return render(request, "my_blog/login.html", {"msg": "用户名不存在"})
        password = request.POST.get("password")
        if password == User.userobj.get(username=username).password:
            return redirect("/" + username + "/")
        else:
            return render(request, "my_blog/login.html", {"msg": "密码错误"})
    return render(request, "my_blog/login.html")


def blog(request, username):
    author = User.userobj.filter(username=username).values("pk")
    authorid = 0
    for i in author:
        authorid = i["pk"]
    blogs = Blog.blogobj.get_queryset().filter(author_id=authorid)
    return render(request, 'my_blog/blog.html', {"blogs":blogs})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            if User.userobj.get_queryset().filter(username=username):
                return render(request, "my_blog/register.html", {"form": form, "msg1": "用户名已注册"})
            gender = form.cleaned_data["gender"]
            email = form.cleaned_data['email']
            birthday = form.cleaned_data['birthday']
            password = form.cleaned_data["password"]
            reptpassword = form.cleaned_data["reptpassword"]
            if password != reptpassword:
                return render(request, "my_blog/register.html", {"form": form, "msg2": "两次密码输入不同"})
            contend = form.cleaned_data['contend']
            newUser = User.userobj.createUser(username, gender, email, password, birthday, contend)
            newUser.save()
            return redirect('/login/')
    else:
        form = RegisterForm()
    return render(request, 'my_blog/register.html', {'form': form})


def newBlog(request, author):
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            authors = User.userobj.get_queryset().filter(username=author)
            for i in authors:
                author = i
            summary = form.cleaned_data["summary"]
            body = request.POST.get("body")
            newblog = Blog.blogobj.createBlog(title, summary, body, author)
            newblog.save()
            author = User.userobj.filter(username=author).values("username")
            username = 0
            for i in author:
                username = i["username"]
            return redirect("/" + username + "/")
        else:
            form = BlogForm()
        return render(request, "my_blog/newblog.html", {"form": form})
    else:
        form = BlogForm()
    return render(request, "my_blog/newblog.html", {"form": form})

templates/my_blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static from staticfiles %}
    <title>{% block title %}{% endblock title %}</title>
    {% block style %}{% endblock style %}
    <script type="text/javascript" charset="utf-8" src="{% static 'my_blog/js/jquery-3.3.1.min.js' %}"></script>
    {% block script %}{% endblock script %}
    <style>
        html{
            margin: 0;
            padding: 0;
        }
        #main {
            width: 100%;
            margin: 0 auto;
            position: relative;
        }
        header{
            width: 100%;
            height: 50px;
            background-color: antiquewhite;
        }
        footer{
            width: 100%;
            height: 50px;
            background-color: deepskyblue;
        }

    </style>
</head>
<body>
    <header></header>

    <div id="main">
        {% block main %}
        {% endblock main %}
    </div>

    <footer></footer>
</body>
</html>

templates/my_blog/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客</title>
</head>
<body>
    <a href="newblog/">写博客</a>
    {% for blog in blogs %}
        <p>{{ blog.title }}--{{ blog.body }}</p>
    {% endfor %}
</body>
</html>

templates/my_blog/index.html
{% extends 'my_blog/base.html' %}
{% load static from staticfiles %}
{% block title %}登陆{% endblock title %}
{% block style %}
    <style type="text/css">
    #form{
        width: 800px;
        height: 500px;
        margin: 0 auto;
        text-align: center;
        vertical-align: ;
        {#position: relative;#}
        }
        </style>
{% endblock style %}

{% block script %}
<script>
    $(document).ready(function () {
        $("#submit").bind("click", function (event) {
            var myurl = '/' + $("#username").val() + '/'
            var Form = document.getElementById("form")
            Form.setAttribute("action", myurl)
        })
        $("#register").bind("click", function (event) {
            var myurl = '/register/'
            var Form = document.getElementById("form")
            Form.setAttribute("action", myurl)
        })
    })
</script>
{% endblock script %}

{% block main %}
    <form id="form" action="" method="post">
        {%  csrf_token %}
        <span>密码或用户名错误，请重新输入</span></br>
        <input id="username" type="text" name="username" placeholder="请输入你的用户名" value=""></br>
        <input type="password" name="password" value=""></br>
        <input id="submit" type="submit" value="登陆">
        <input id="register" type="submit" value="注册">
    </form>
{% endblock main %}

templates/my_blog/login.html
{% extends 'my_blog/base.html' %}
{% load static from staticfiles %}
{% block title %}登陆{% endblock title %}
{% block style %}
    <style type="text/css">
    #form{
        width: 800px;
        height: 500px;
        margin: 0 auto;
        text-align: center;
        }
    span {
        color: red;
    }
    </style>
{% endblock style %}

{% block script %}

{% endblock script %}

{% block main %}
    <form id="form" action="/index/" method="post">
        {%  csrf_token %}
        <input id="username" type="text" name="username" placeholder="请输入你的用户名" value=""></br>
        <input type="password" name="password" value=""></br>
        <input id="submit" type="submit" value="登陆">
        <a href="register" ><input id="register" type="button" value="注册"></a><br/>
        <span>{{ msg }}</span>
    </form>
{% endblock main %}

templates/my_blog/newblog.html
{% extends 'my_blog/base.html' %}
{% load static from staticfiles %}
{% block title %}新博客{% endblock title %}
{% block style %}

{% endblock style %}
{% block script %}
<script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        'mode': 'textareas',
        'theme': 'advanced',
        'width':800,
        'height':900,
    })
</script>
{% endblock script %}
{% block main %}
    <form id="form" action="" method="post">
    {% csrf_token %}
        标题：{{ form.title }}<br/>
        作者：{{ form.author }}<br/>
        摘要：{{ form.summary }}<br/>
        文章：<textarea name="body"></textarea> <br/>
        <input id="submit" type="submit" value="保存" />
    </form>
{% endblock main %}

templates/my_blog/register.html
{% extends 'my_blog/base.html' %}
{% load static from staticfiles %}
{% block title %}注册{% endblock title %}
{% block style %}
    <style type="text/css">
        span {
            color: red;
        }
        #tips {
            display: none;
        }
    </style>
{% endblock style %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
        $("#id_reptpassword").bind("blur", function (event) {
            if ($("#id_reptpassword").val() != $("#id_password").val()) {
                $("#error").css("display", "inline")
            }
            else {
                $("#error").css("display", "none")
            }
        })
        $("#id_password").bind("blur", function (event) {
            if ($("#id_reptpassword").val() != $("#id_password").val()) {
                $("#error").css("display", "inline")
            }
            else {
                $("#error").css("display", "none")
            }
        })
        $("#id_birthday").bind("focus", function (event) {
                $("#tips").css("display", "inline")
        })
        $("#id_birthday").bind("blur", function (event) {
                $("#tips").css("display", "none")
        })
    })
</script>
{% endblock script %}
{% block main %}
    <form id="form" action="" method="post">
    {% csrf_token %}
            昵称：{{ form.username }}<span>{{ msg1 }}</span><br/>
            性别：{{ form.gender }}<br/>
            邮箱：{{ form.email }}<br/>
            密码：{{ form.password }}<br/>
            确认密码：{{ form.reptpassword }}
            <span>{{ msg2 }}</span><br/>
            生日：{{ form.birthday }}
            <span id="tips">形式为(年/月/日，如：1993/08/27)</span><br/>
            简介：{{ form.contend }}<br/>
        <input id="submit" type="submit" value="注册" />
    </form>
    <div>
        <a href="/">已有账号登录</a>
    </div>
{% endblock main %}